<?php require ROOT_PATH . '/app/views/admin/partials/header.php'; ?>
<form method="post" action="/admin/services<?= $service ? '?id=' . (int) $service['id'] : '?new=1' ?>">
    <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int) ($service['id'] ?? 0) ?>">
    <div class="editor-toolbar"><a class="admin-link" href="/admin/services">→ العودة</a><div><button class="admin-button secondary" name="action" value="save_service">حفظ كمسودة</button><button class="admin-button" name="action" value="publish_service">حفظ ونشر</button></div></div>
    <section class="admin-card editor-card"><div class="card-heading"><div><p>الإعدادات الأساسية</p><h2><?= $service ? 'تعديل الخدمة' : 'خدمة جديدة' ?></h2></div></div><div class="admin-form-grid"><label><span>المعرّف اللاتيني للرابط</span><input dir="ltr" name="slug" pattern="[a-z0-9-]+" value="<?= e($service['slug'] ?? '') ?>" required></label><label><span>الأيقونة</span><select name="icon"><?php foreach (['clearance'=>'تخليص','document'=>'مستند','consultancy'=>'استشارة','tracking'=>'متابعة','resolution'=>'تسوية'] as $key=>$label): ?><option value="<?= $key ?>"<?= ($service['icon'] ?? 'document') === $key ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label><span>الترتيب</span><input type="number" name="sort_order" min="0" max="999" value="<?= (int) ($service['sort_order'] ?? 10) ?>"></label><label class="check-label"><input type="checkbox" name="is_visible" value="1"<?= !$service || $service['is_visible'] ? ' checked' : '' ?>><span>إظهار الخدمة في الموقع</span></label></div></section>
    <?php foreach (['ar'=>'العربية','en'=>'English','ku'=>'کوردی'] as $langCode=>$langLabel): $tr=$translations[$langCode] ?? []; ?>
        <section class="admin-card editor-card"><div class="card-heading"><div><p><?= e($langLabel) ?></p><h2>محتوى الخدمة</h2></div><span class="status <?= e($tr['translation_status'] ?? 'needs_review') ?>"><?= ($tr['translation_status'] ?? '') === 'approved' ? 'معتمدة' : 'بحاجة إلى مراجعة' ?></span></div><div class="admin-form-grid"><label class="full"><span>اسم الخدمة</span><input name="translations[<?= $langCode ?>][name]" value="<?= e($tr['draft_name'] ?? '') ?>" required></label><label class="full"><span>وصف الخدمة</span><textarea name="translations[<?= $langCode ?>][description]" rows="4" required><?= e($tr['draft_description'] ?? '') ?></textarea></label><label><span>حالة الترجمة</span><select name="translations[<?= $langCode ?>][status]"><option value="approved"<?= ($tr['translation_status'] ?? '') === 'approved' ? ' selected' : '' ?>>معتمدة</option><option value="needs_review"<?= ($tr['translation_status'] ?? '') !== 'approved' ? ' selected' : '' ?>>بحاجة إلى مراجعة</option></select></label></div></section>
    <?php endforeach; ?>
</form>
<?php if ($service): ?><section class="admin-card danger-zone"><div><h2>حذف الخدمة</h2><p>لن تُحذف طلبات التواصل القديمة، ولكن سيُزال ارتباطها بالخدمة.</p></div><form method="post" action="/admin/services"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int) $service['id'] ?>"><button class="admin-button danger" name="action" value="delete_service" data-confirm="هل تريد حذف هذه الخدمة نهائياً؟">حذف الخدمة</button></form></section><?php endif; ?>
<?php require ROOT_PATH . '/app/views/admin/partials/footer.php'; ?>
