<?php require ROOT_PATH . '/app/views/admin/partials/header.php'; ?>
<form method="post" action="/admin/settings">
    <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_settings">
    <section class="admin-card editor-card"><div class="card-heading"><div><p>تظهر للعامة عند توفرها</p><h2>هوية الشركة وبيانات الاتصال</h2></div></div><div class="admin-form-grid"><label class="full"><span>الاسم القانوني بالعربية</span><input name="company_legal_ar" value="<?= e($settingsAdmin['company_legal_ar'] ?? '') ?>" required></label><label><span>الاسم الإنجليزي المعتمد</span><input dir="ltr" name="company_name_en" value="<?= e($settingsAdmin['company_name_en'] ?? '') ?>"></label><label><span>الهاتف</span><input dir="ltr" name="phone" value="<?= e($settingsAdmin['phone'] ?? '') ?>"></label><label><span>رقم واتساب - أرقام فقط مع رمز الدولة</span><input dir="ltr" name="whatsapp" value="<?= e($settingsAdmin['whatsapp'] ?? '') ?>"></label><label><span>البريد الإلكتروني</span><input dir="ltr" type="email" name="email" value="<?= e($settingsAdmin['email'] ?? '') ?>"></label><label class="full"><span>العنوان بالعربية</span><input name="address_ar" value="<?= e($settingsAdmin['address_ar'] ?? '') ?>"></label><label class="full"><span>العنوان بالإنجليزية</span><input dir="ltr" name="address_en" value="<?= e($settingsAdmin['address_en'] ?? '') ?>"></label><label class="full"><span>العنوان بالكوردية</span><input name="address_ku" value="<?= e($settingsAdmin['address_ku'] ?? '') ?>"></label></div></section>
    <section class="admin-card editor-card"><div class="card-heading"><div><p>العناصر الفارغة تبقى مخفية</p><h2>معلومات اختيارية مؤكدة فقط</h2></div></div><div class="admin-form-grid"><label><span>ساعات العمل - عربي</span><input name="working_hours_ar" value="<?= e($settingsAdmin['working_hours_ar'] ?? '') ?>"></label><label><span>ساعات العمل - English</span><input dir="ltr" name="working_hours_en" value="<?= e($settingsAdmin['working_hours_en'] ?? '') ?>"></label><label><span>ساعات العمل - کوردی</span><input name="working_hours_ku" value="<?= e($settingsAdmin['working_hours_ku'] ?? '') ?>"></label><label><span>Facebook</span><input dir="ltr" type="url" name="facebook" value="<?= e($settingsAdmin['facebook'] ?? '') ?>"></label><label><span>Instagram</span><input dir="ltr" type="url" name="instagram" value="<?= e($settingsAdmin['instagram'] ?? '') ?>"></label><label><span>LinkedIn</span><input dir="ltr" type="url" name="linkedin" value="<?= e($settingsAdmin['linkedin'] ?? '') ?>"></label><label class="full"><span>رابط الخريطة المؤكد</span><input dir="ltr" type="url" name="map_url" value="<?= e($settingsAdmin['map_url'] ?? '') ?>"></label></div><button class="admin-button" type="submit">حفظ البيانات</button></section>
</form>
<section class="admin-card editor-card"><div class="card-heading"><div><p>PNG / JPG / WebP / AVIF أو PDF</p><h2>رفع الوسائط</h2></div><span class="help-text">الصور 8MB، الملف التعريفي 100MB</span></div><form class="admin-form-grid" method="post" action="/admin/settings" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="upload_media"><label><span>موضع الملف</span><select name="slot" required><option value="logo">الشعار</option><option value="hero">الصورة الرئيسية</option><option value="profile">الملف التعريفي PDF</option></select></label><label><span>الملف</span><input type="file" name="media_file" accept="image/jpeg,image/png,image/webp,image/avif,application/pdf" required></label><label><span>النص البديل - عربي</span><input name="alt_ar"></label><label><span>Alt text - English</span><input dir="ltr" name="alt_en"></label><label><span>دەقی جێگرەوە - کوردی</span><input name="alt_ku"></label><div class="form-action"><button class="admin-button" type="submit">رفع وربط الملف</button></div></form><?php if ($media): ?><div class="media-history"><h3>آخر الملفات المرفوعة</h3><ul><?php foreach ($media as $item): ?><li><span><?= e($item['media_type']) ?></span><a dir="ltr" href="<?= e($item['file_path']) ?>" target="_blank"><?= e($item['original_name']) ?></a><small><?= number_format($item['file_size']/1024, 0) ?> KB</small></li><?php endforeach; ?></ul></div><?php endif; ?></section>
<section class="admin-card missing-content"><h2>نواقص المحتوى الحالية</h2><p>لم ترد ساعات العمل أو روابط الشبكات الاجتماعية أو رابط خريطة مؤكد في الملف التعريفي. لذلك بقيت حقولها فارغة ولا تظهر للعامة.</p></section>
<?php require ROOT_PATH . '/app/views/admin/partials/footer.php'; ?>

