<?php

declare(strict_types=1);

return [
    'pages' => [
        'home' => [
            'ar' => [
                'seo_title' => 'شركة المواهب | الإخراج والتخليص الكمركي في العراق',
                'seo_description' => 'شركة عراقية متخصصة في التخليص الكمركي للبضائع وإعداد المعاملات والاستشارات ومتابعة مراحل التخليص وتسوية القضايا الكمركية.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'وضوح المسار ودقة الإجراءات',
                    'hero_title' => 'مسار أوضح لمعاملاتك الكمركية.',
                    'hero_description' => 'ننجز إجراءات التخليص ونعدّ الوثائق ونقدّم الاستشارة بدقة ومهنية عبر المنافذ العراقية البرية والبحرية والجوية.',
                    'about_title' => 'خبرة عملية، ورؤية تتجدد.',
                    'about_body' => 'تأسست شركة المواهب للإخراج والتخليص الكمركي بخبرة عملية ورؤية متجددة في سوق الخدمات اللوجستية. نبني عملنا على العلاقات المهنية مع الجهات الكمركية، والالتزام، والدقة، والشفافية.',
                    'services_title' => 'خدمات تضبط كل مرحلة.',
                    'services_intro' => 'من إعداد المعاملة إلى متابعة مراحل التخليص، يركّز فريقنا على وضوح المتطلبات وسلامة الإجراءات.',
                    'why_title' => 'لماذا المواهب؟',
                    'why_items' => "علاقات قوية مع الدوائر الكمركية.\nسرعة في إنجاز المعاملات.\nالتزام كامل بتعليمات الجمارك العراقية.\nاستشارات مجانية ودعم متواصل للعملاء.\nحلول مبتكرة ومتكاملة لتحديات التخليص الكمركي.",
                    'scope_title' => 'نعمل حيث تعبر تجارتك.',
                    'scope_body' => 'خدمات التخليص للبضائع عبر المنافذ الحدودية العراقية البرية والبحرية والجوية، مع معرفة بالإجراءات والمتطلبات المرتبطة بكل مسار.',
                    'profile_title' => 'الصورة الكاملة، في ملف واحد.',
                    'profile_text' => 'اطّلع على الملف التعريفي الرسمي لعام 2026 لمعرفة الرؤية والخدمات والهيكل المؤسسي والمشروع الوارد فيه.',
                    'cta_title' => 'لديك معاملة تحتاج إلى مسار واضح؟',
                    'cta_text' => 'أرسل تفاصيلها، وسيطّلع فريقنا على متطلباتك ويتواصل معك.',
                ],
            ],
            'en' => [
                'seo_title' => 'Al-Mawaheb Co. | Export and Customs Clearance in Iraq',
                'seo_description' => 'An Iraqi company specializing in cargo customs clearance, documentation, customs consultancy, shipment monitoring, and dispute resolution.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'A clear route. Precise procedures.',
                    'hero_title' => 'A clearer path through customs.',
                    'hero_description' => 'We manage clearance procedures, prepare documentation, and provide professional guidance across Iraq’s land, sea, and air border crossings.',
                    'about_title' => 'Practical expertise. A forward-looking vision.',
                    'about_body' => 'Al-Mawaheb was established with practical expertise and a renewed vision for the logistics services sector. Our work is built on professional relationships with customs authorities and a commitment to accuracy, transparency, and compliance.',
                    'services_title' => 'Services aligned at every stage.',
                    'services_intro' => 'From preparing a transaction to monitoring clearance stages, our team focuses on clear requirements and sound procedures.',
                    'why_title' => 'Why Al-Mawaheb?',
                    'why_items' => "Strong relationships with customs authorities.\nFast processing and completion of customs procedures.\nFull compliance with Iraqi customs regulations and instructions.\nFree consultations and continuous customer support.\nIntegrated solutions for customs clearance challenges.",
                    'scope_title' => 'Present where your trade moves.',
                    'scope_body' => 'Cargo customs clearance through Iraq’s land, sea, and air border crossings, supported by knowledge of the procedures and requirements associated with each route.',
                    'profile_title' => 'The full picture, in one profile.',
                    'profile_text' => 'View the official 2026 company profile for the stated vision, services, organizational structure, and featured project.',
                    'cta_title' => 'Have a transaction that needs a clear route?',
                    'cta_text' => 'Share the details and our team will review your requirements and contact you.',
                ],
            ],
            'ku' => [
                'seo_title' => 'کۆمپانیای المواهب | دەرکردن و پاککردنەوەی گومرگی لە عێراق',
                'seo_description' => 'کۆمپانیایەکی عێراقی پسپۆڕ لە پاککردنەوەی گومرگی، ئامادەکردنی بەڵگەنامەکان، ڕاوێژکاری و چارەسەرکردنی کێشە گومرگییەکان.',
                'status' => 'needs_review',
                'content' => [
                    'eyebrow' => 'ڕوونیی ڕێڕەو و وردیی ڕێکارەکان',
                    'hero_title' => 'ڕێگایەکی ڕوونتر بۆ مامەڵە گومرگییەکانت.',
                    'hero_description' => 'ڕێکارەکانی پاککردنەوەی گومرگی بەڕێوە دەبەین، بەڵگەنامەکان ئامادە دەکەین و ڕاوێژی پیشەیی لە دەروازە وشکانی، دەریایی و ئاسمانییەکانی عێراق پێشکەش دەکەین.',
                    'about_title' => 'شارەزایی کرداری و دیدێکی نوێبووەوە.',
                    'about_body' => 'کۆمپانیای المواهب بە شارەزایی کرداری و دیدێکی نوێبووەوە لە بازاڕی خزمەتگوزارییە لۆجستییەکان دامەزراوە. کارەکانمان لەسەر پەیوەندییە پیشەییەکان لەگەڵ دەسەڵاتە گومرگییەکان و پابەندبوون بە وردی، ڕوونی و یاساکان بنیاد نراوە.',
                    'services_title' => 'خزمەتگوزاری بۆ ڕێکخستنی هەموو قۆناغێک.',
                    'services_intro' => 'لە ئامادەکردنی مامەڵە تا بەدواداچوونی قۆناغەکانی پاککردنەوە، تیمەکەمان جەخت لە ڕوونیی پێداویستییەکان و دروستیی ڕێکارەکان دەکاتەوە.',
                    'why_title' => 'بۆچی المواهب؟',
                    'why_items' => "پەیوەندیی بەهێز لەگەڵ فەرمانگە گومرگییەکان.\nخێرایی لە تەواوکردنی مامەڵەکان.\nپابەندبوونی تەواو بە ڕێنماییە گومرگییەکانی عێراق.\nڕاوێژی بێبەرامبەر و پشتگیری بەردەوام بۆ کڕیاران.\nچارەسەری نوێ و یەکگرتوو بۆ ئاستەنگەکانی پاککردنەوەی گومرگی.",
                    'scope_title' => 'لەو شوێنەین کە بازرگانییەکەت تێدەپەڕێت.',
                    'scope_body' => 'خزمەتگوزاریی پاککردنەوەی گومرگیی کاڵا لە دەروازە وشکانی، دەریایی و ئاسمانییەکانی عێراق، پشتبەستوو بە زانیاریی ڕێکار و پێداویستیی هەر ڕێڕەوێک.',
                    'profile_title' => 'وێنەی تەواو لە یەک ناسنامەدا.',
                    'profile_text' => 'ناسنامەی فەرمی کۆمپانیا بۆ ساڵی 2026 ببینە بۆ ناسینی دید، خزمەتگوزارییەکان، پێکهاتەی دامەزراوەیی و پڕۆژەی ناوبراو.',
                    'cta_title' => 'مامەڵەیەکت هەیە کە پێویستی بە ڕێڕەوێکی ڕوونە؟',
                    'cta_text' => 'وردەکارییەکان بنێرە؛ تیمەکەمان پێداویستییەکانت دەبینێتەوە و پەیوەندیت پێوە دەکات.',
                ],
            ],
        ],
        'about' => [
            'ar' => [
                'seo_title' => 'من نحن | شركة المواهب',
                'seo_description' => 'تعرّف على شركة المواهب ورؤيتها ورسالتها وقيمها وفريقها في مجال الإخراج والتخليص الكمركي.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'من نحن',
                    'title' => 'الدقة ليست تفصيلاً. إنها طريقة عمل.',
                    'intro' => 'شركة المواهب للاخراج والتخليص الكمركي محدودة المسؤولية، شركة عراقية تعمل على تسهيل الإجراءات الكمركية وحركة البضائع بخدمات مهنية واضحة.',
                    'company_title' => 'مقدمة تعريفية',
                    'company_body' => 'تأسست الشركة بخبرة عملية ورؤية متجددة في سوق الخدمات اللوجستية، واستطاعت بناء علاقات واسعة مع الجهات الكمركية وكسب ثقة شركات ومؤسسات وأفراد داخل العراق والمنطقة. تواصل الشركة تقديم خدمات التخليص والحلول اللوجستية الواردة في ملفها بما يسهّل التجارة ويلبّي احتياجات العملاء مع الحفاظ على الشفافية والدقة والتميّز التشغيلي.',
                    'vision_title' => 'رؤيتنا',
                    'vision' => 'أن نكون الاسم الأول والمرجع الأوثق في مجال التخليص الكمركي والخدمات اللوجستية، وأن نقدم حلولاً متطورة ترتقي بتجربة عملائنا نحو مستويات جديدة من الاحترافية والكفاءة والأمان، بما يسهم في تسهيل حركة التجارة ودعم النمو الاقتصادي المستدام.',
                    'mission_title' => 'رسالتنا',
                    'mission' => 'تسهيل العمليات الكمركية وتسريع حركة البضائع من خلال خدمات احترافية متكاملة، وتطوير الحلول باستمرار، والاستثمار في الكفاءات البشرية والتقنيات الحديثة، بما يضمن الدقة والكفاءة والالتزام مع التمسك بالنزاهة والشفافية والجودة.',
                    'values_title' => 'قيمنا',
                    'values' => "الالتزام|الوفاء بالتزاماتنا تجاه عملائنا وشركائنا والعمل بمسؤولية لتحقيق أفضل النتائج.\nالاحترافية|العناية بأدق التفاصيل واعتماد أفضل الممارسات المهنية.\nالابتكار|تطوير حلول وأدوات حديثة تسهم في تبسيط وتسريع الإجراءات.\nالشفافية|الوضوح والمصداقية في التعاملات والمراسلات وبناء علاقات طويلة الأمد.",
                    'team_title' => 'فريق العمل',
                    'team_body' => 'يضم فريق الشركة متخصصين في التخليص الكمركي يمتلكون خبرة عملية ومعرفة بالأنظمة والتعليمات. ويحرص الفريق على التطور المهني ومواكبة التغييرات لخدمة العملاء بكفاءة ودقة.',
                    'future_title' => 'رؤيتنا المستقبلية',
                    'future_body' => 'تطمح الشركة إلى توسيع خدماتها لتشمل جميع المنافذ العراقية، وبناء شبكة شراكات استراتيجية مع شركات نقل عالمية، والاستثمار في التقنيات الرقمية لتقديم خدمات تخليص إلكترونية متطورة.',
                ],
            ],
            'en' => [
                'seo_title' => 'About Al-Mawaheb Co.',
                'seo_description' => 'Learn about Al-Mawaheb Co., its vision, mission, values, and team in customs clearance and related logistics services.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'About us',
                    'title' => 'Accuracy is not a detail. It is how we work.',
                    'intro' => 'Al-Mawaheb Co. is an Iraqi limited liability company that facilitates customs procedures and the movement of goods through clear, professional services.',
                    'company_title' => 'Introduction',
                    'company_body' => 'Established with practical expertise and a forward-looking vision in the logistics services sector, the company has built broad professional relationships with customs authorities and earned the trust of companies, institutions, and individuals across Iraq and the region. Al-Mawaheb continues to provide the customs clearance and logistics solutions stated in its company profile, facilitating trade while maintaining transparency, accuracy, and operational excellence.',
                    'vision_title' => 'Our vision',
                    'vision' => 'To be the first choice and most trusted reference in customs clearance and logistics services, delivering advanced solutions that elevate our clients’ experience through professionalism, efficiency, and security while facilitating trade and supporting sustainable economic growth.',
                    'mission_title' => 'Our mission',
                    'mission' => 'To facilitate customs procedures and accelerate the movement of goods through integrated professional services, continuous improvement, investment in skilled professionals, and modern technologies, ensuring accuracy, efficiency, compliance, integrity, transparency, and quality.',
                    'values_title' => 'Our values',
                    'values' => "Commitment|Fulfilling our obligations to clients and partners with responsibility and reliability.\nProfessionalism|Attending to every detail and following sound professional practices.\nInnovation|Developing modern solutions and tools that simplify and accelerate procedures.\nTransparency|Maintaining honesty and clarity in communications and business dealings.",
                    'team_title' => 'Our team',
                    'team_body' => 'The company’s team includes customs clearance specialists with practical experience and knowledge of relevant regulations and instructions. The team is committed to professional development and keeping up with changes to serve clients with efficiency and accuracy.',
                    'future_title' => 'Our future vision',
                    'future_body' => 'The company aspires to expand its services across all Iraqi border crossings, build strategic partnerships with global transportation companies, and invest in digital technologies for advanced electronic customs clearance services.',
                ],
            ],
            'ku' => [
                'seo_title' => 'دەربارەی کۆمپانیای المواهب',
                'seo_description' => 'زانیاری دەربارەی کۆمپانیای المواهب، دید، ئەرک، بەهاکان و تیمەکەی لە بواری پاککردنەوەی گومرگی.',
                'status' => 'needs_review',
                'content' => [
                    'eyebrow' => 'دەربارەی ئێمە',
                    'title' => 'وردی تەنها وردەکاری نییە؛ شێوازی کارکردنمانە.',
                    'intro' => 'کۆمپانیای المواهب بۆ دەرکردن و پاککردنەوەی گومرگی، کۆمپانیایەکی عێراقی سنووردارە کە بە خزمەتگوزاریی پیشەیی و ڕوون ڕێکارە گومرگییەکان و جوڵەی کاڵا ئاسان دەکات.',
                    'company_title' => 'ناساندن',
                    'company_body' => 'کۆمپانیا بە شارەزایی کرداری و دیدێکی پێشکەوتوو لە کەرتی خزمەتگوزارییە لۆجستییەکان دامەزراوە و پەیوەندیی پیشەیی فراوانی لەگەڵ دەسەڵاتە گومرگییەکان دروست کردووە. بە ڕوونی، وردی و کارایی، خزمەتگوزارییە گومرگی و لۆجستییە باسکراوەکان لە ناسنامەی کۆمپانیا پێشکەش دەکات.',
                    'vision_title' => 'دیدمان',
                    'vision' => 'ببینە یەکەم هەڵبژاردە و متمانەپێکراوترین سەرچاوە لە پاککردنەوەی گومرگی و خزمەتگوزارییە لۆجستییەکان، بە پێشکەشکردنی چارەسەری پێشکەوتوو کە ئەزموونی کڕیار بەرز دەکاتەوە و بازرگانی و گەشەی ئابووریی بەردەوام پشتگیری دەکات.',
                    'mission_title' => 'ئەرکمان',
                    'mission' => 'ئاسانکردنی ڕێکارە گومرگییەکان و خێراکردنی جوڵەی کاڵا بە خزمەتگوزاریی پیشەیی یەکگرتوو، پەرەپێدانی بەردەوام، وەبەرهێنان لە توانای مرۆیی و تەکنەلۆژیای نوێ، لەگەڵ وردی، کارایی، پابەندی، دەستپاکی و ڕوونی.',
                    'values_title' => 'بەهاکانمان',
                    'values' => "پابەندی|جێبەجێکردنی پابەندییەکانمان بەرامبەر کڕیار و هاوبەشەکان بە بەرپرسیارییەوە.\nپیشەییبوون|گرنگیدان بە هەموو وردەکارییەک و پەیڕەوکردنی باشترین شێوازە پیشەییەکان.\nنوێکاری|پەرەپێدانی چارەسەر و ئامرازی نوێ بۆ ئاسان و خێراکردنی ڕێکارەکان.\nڕوونی|ڕاستگۆیی و ڕوونی لە پەیوەندی و مامەڵە بازرگانییەکان.",
                    'team_title' => 'تیمی کار',
                    'team_body' => 'تیمی کۆمپانیا پسپۆڕانی پاککردنەوەی گومرگی لەخۆدەگرێت کە شارەزایی کرداری و زانیارییان لە یاسا و ڕێنماییە پەیوەندیدارەکان هەیە. تیمەکە پابەندە بە پەرەپێدانی پیشەیی و خزمەتکردنی کڕیار بە کارایی و وردی.',
                    'future_title' => 'دیدی داهاتوومان',
                    'future_body' => 'کۆمپانیا ئامانجیەتی خزمەتگوزارییەکانی بۆ هەموو دەروازە گومرگییەکانی عێراق فراوان بکات، هاوبەشیی ستراتیژی لەگەڵ کۆمپانیا گواستنەوە جیهانییەکان دروست بکات و لە تەکنەلۆژیای دیجیتاڵ وەبەرهێنان بکات.',
                ],
            ],
        ],
        'services' => [
            'ar' => [
                'seo_title' => 'خدماتنا | شركة المواهب',
                'seo_description' => 'خدمات التخليص الكمركي وإعداد المعاملات والاستشارات ومتابعة الشحنات وتسوية القضايا الكمركية.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'خدماتنا',
                    'title' => 'كل إجراء في موضعه الصحيح.',
                    'intro' => 'خمس خدمات مترابطة تغطي متطلبات المعاملة الكمركية من تجهيز الوثائق إلى المعالجة والمتابعة.',
                ],
            ],
            'en' => [
                'seo_title' => 'Customs Clearance Services | Al-Mawaheb Co.',
                'seo_description' => 'Customs clearance, documentation and processing, consultancy, shipment monitoring, and customs dispute resolution.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'Our services',
                    'title' => 'Every procedure in the right place.',
                    'intro' => 'Five connected services covering customs transaction requirements from document preparation to follow-up and resolution.',
                ],
            ],
            'ku' => [
                'seo_title' => 'خزمەتگوزارییەکانمان | کۆمپانیای المواهب',
                'seo_description' => 'پاککردنەوەی گومرگی، ئامادەکردنی بەڵگەنامە، ڕاوێژکاری، بەدواداچوونی بار و چارەسەرکردنی کێشە گومرگییەکان.',
                'status' => 'needs_review',
                'content' => [
                    'eyebrow' => 'خزمەتگوزارییەکانمان',
                    'title' => 'هەر ڕێکارێک لە شوێنی دروستی خۆیدا.',
                    'intro' => 'پێنج خزمەتگوزاریی پەیوەست کە پێداویستییەکانی مامەڵەی گومرگی لە ئامادەکردنی بەڵگەنامە تا بەدواداچوون و چارەسەرکردن دەگرێتەوە.',
                ],
            ],
        ],
        'contact' => [
            'ar' => [
                'seo_title' => 'اتصل بنا | شركة المواهب',
                'seo_description' => 'تواصل مع شركة المواهب في بغداد للاستفسار عن خدمات الإخراج والتخليص الكمركي.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'اتصل بنا',
                    'title' => 'ابدأ بالمتطلبات. نوضح لك المسار.',
                    'intro' => 'أرسل تفاصيل معاملتك أو استفسارك، وسيتواصل معك فريق الشركة عبر الوسيلة التي تفضّلها.',
                    'form_title' => 'تفاصيل طلبك',
                    'form_intro' => 'قدّم المعلومات الأساسية فقط. يمكنك إضافة أي تفاصيل مفيدة داخل وصف الطلب.',
                ],
            ],
            'en' => [
                'seo_title' => 'Contact Al-Mawaheb Co.',
                'seo_description' => 'Contact Al-Mawaheb Co. in Baghdad with an enquiry about export and customs clearance services.',
                'status' => 'approved',
                'content' => [
                    'eyebrow' => 'Contact us',
                    'title' => 'Start with the requirements. We clarify the route.',
                    'intro' => 'Share your transaction details or enquiry and the company team will contact you using your preferred method.',
                    'form_title' => 'Your request details',
                    'form_intro' => 'Provide only the essential information. Add any useful context in the request description.',
                ],
            ],
            'ku' => [
                'seo_title' => 'پەیوەندی بە کۆمپانیای المواهب',
                'seo_description' => 'بۆ پرسیار دەربارەی دەرکردن و پاککردنەوەی گومرگی پەیوەندی بە کۆمپانیای المواهب لە بەغداوە بکە.',
                'status' => 'needs_review',
                'content' => [
                    'eyebrow' => 'پەیوەندیمان پێوە بکە',
                    'title' => 'لە پێداویستییەکانەوە دەست پێ بکە؛ ئێمە ڕێڕەوەکە ڕوون دەکەینەوە.',
                    'intro' => 'وردەکاریی مامەڵە یان پرسیارەکەت بنێرە و تیمی کۆمپانیا لە ڕێگەی شێوازی دڵخوازت پەیوەندیت پێوە دەکات.',
                    'form_title' => 'وردەکارییەکانی داواکارییەکەت',
                    'form_intro' => 'تەنها زانیارییە سەرەکییەکان پێشکەش بکە. هەر وردەکارییەکی بەسوود لە وەسفی داواکاری زیاد بکە.',
                ],
            ],
        ],
    ],
    'services' => [
        [
            'slug' => 'cargo-customs-clearance', 'icon' => 'clearance', 'sort' => 1,
            'translations' => [
                'ar' => ['التخليص الكمركي للبضائع', 'تخليص جميع أنواع البضائع في المنافذ الحدودية العراقية البرية والبحرية والجوية، مع مراعاة الأنظمة والتعليمات النافذة.', 'approved'],
                'en' => ['Customs Clearance Services', 'Customs clearance for all types of cargo through Iraq’s land, sea, and air border crossings, with attention to applicable regulations and requirements.', 'approved'],
                'ku' => ['پاککردنەوەی گومرگی بۆ کاڵا', 'پاککردنەوەی گومرگی بۆ جۆرەکانی کاڵا لە دەروازە وشکانی، دەریایی و ئاسمانییەکانی عێراق، لەگەڵ پابەندبوون بە یاسا و ڕێنماییەکان.', 'needs_review'],
            ],
        ],
        [
            'slug' => 'customs-documentation', 'icon' => 'document', 'sort' => 2,
            'translations' => [
                'ar' => ['إعداد المعاملات الكمركية', 'تجهيز وتدقيق المستندات والوثائق المطلوبة للمعاملة بما يساعد على انسيابية الإجراءات وتجنب التأخيرات.', 'approved'],
                'en' => ['Customs Documentation & Processing', 'Preparation, review, and management of the customs documents and paperwork required for smooth processing and fewer delays.', 'approved'],
                'ku' => ['ئامادەکردنی مامەڵە گومرگییەکان', 'ئامادەکردن و پشکنینی بەڵگەنامە و دۆکیومێنتە پێویستەکان بۆ ڕەوانیی ڕێکارەکان و کەمکردنەوەی دواکەوتن.', 'needs_review'],
            ],
        ],
        [
            'slug' => 'customs-consultancy', 'icon' => 'consultancy', 'sort' => 3,
            'translations' => [
                'ar' => ['استشارات كمركية', 'تقديم حلول واستشارات متخصصة بشأن الأنظمة واللوائح الكمركية، لمساعدة العملاء على فهم المتطلبات واتخاذ قرارات مدروسة.', 'approved'],
                'en' => ['Customs Consultancy Services', 'Specialized consultancy on customs regulations, procedures, and compliance requirements to support informed decisions.', 'approved'],
                'ku' => ['ڕاوێژکاریی گومرگی', 'پێشکەشکردنی ڕاوێژ و چارەسەری پسپۆڕانە دەربارەی یاسا، ڕێکار و پێداویستییە گومرگییەکان بۆ بڕیاری ئاگادارانە.', 'needs_review'],
            ],
        ],
        [
            'slug' => 'shipment-monitoring', 'icon' => 'tracking', 'sort' => 4,
            'translations' => [
                'ar' => ['متابعة الشحنات', 'متابعة وضع الشحنات ومراحل التخليص من الوصول حتى الاستلام النهائي، وتزويد العملاء بتحديثات وتقارير دورية.', 'approved'],
                'en' => ['Shipment Tracking & Monitoring', 'Monitoring shipments from arrival through final clearance and delivery, with regular status updates and progress reports.', 'approved'],
                'ku' => ['بەدواداچوونی بارەکان', 'بەدواداچوونی بار لە کاتی گەیشتن تا پاککردنەوە و وەرگرتنی کۆتایی، لەگەڵ نوێکردنەوە و ڕاپۆرتی بەردەوام بۆ کڕیار.', 'needs_review'],
            ],
        ],
        [
            'slug' => 'customs-dispute-resolution', 'icon' => 'resolution', 'sort' => 5,
            'translations' => [
                'ar' => ['تسوية القضايا الكمركية', 'المساعدة في معالجة الإشكالات والقضايا المرتبطة بالإخراج الكمركي والتنسيق الفعّال مع الجهات المعنية.', 'approved'],
                'en' => ['Customs Dispute Resolution', 'Assistance with customs-related issues, disputes, and procedural challenges through effective coordination with the relevant authorities.', 'approved'],
                'ku' => ['چارەسەرکردنی کێشە گومرگییەکان', 'یارمەتیدان لە چارەسەرکردنی کێشە و گرفتەکانی دەرکردنی گومرگی بە هاوکاریی کاریگەر لەگەڵ لایەنە پەیوەندیدارەکان.', 'needs_review'],
            ],
        ],
    ],
    'settings' => [
        'company_legal_ar' => 'شركة المواهب للاخراج والتخليص الكمركي محدودة المسؤولية',
        'company_name_en' => 'Al-Mawaheb Co.',
        'phone' => '+964 786 953 3836',
        'whatsapp' => '9647869533836',
        'email' => 'info@almawaheb-co.com',
        'address_ar' => 'العراق - بغداد - المنصور - شارع الأميرات، محلة 601 - زقاق 18 - دار 1/30',
        'address_en' => 'Iraq - Baghdad - Al-Mansour - Al-Ameerat St., District 601 - St. 18 - House 1/30',
        'address_ku' => 'عێراق - بەغدا - مەنسوور - شەقامی ئەمیرات، گەڕەکی 601 - کۆڵانی 18 - خانووی 1/30',
        'working_hours_ar' => '',
        'working_hours_en' => '',
        'working_hours_ku' => '',
        'facebook' => '',
        'instagram' => '',
        'linkedin' => '',
        'map_url' => '',
        'media_logo' => '/assets/img/logo.png',
        'media_hero' => '/assets/img/hero-team.webp',
        'media_profile' => '/assets/files/al-mawaheb-company-profile-2026.pdf',
    ],
];
